/**
 * Canonical domain events published after Firestore (or local) writes succeed.
 * Sync / analytics / notifications subscribe — never React components.
 */
export const EventTypes = {
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_UPDATED: "INVOICE_UPDATED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  INVENTORY_CHANGED: "INVENTORY_CHANGED",
  INVENTORY_MOVEMENT_CREATED: "INVENTORY_MOVEMENT_CREATED",
  STOCK_ADJUSTED: "STOCK_ADJUSTED",
  CATEGORY_CREATED: "CATEGORY_CREATED",
  CATEGORY_UPDATED: "CATEGORY_UPDATED",
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  REFUND_CREATED: "REFUND_CREATED",
  REFUND_UPDATED: "REFUND_UPDATED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  NOTIFICATION_QUEUED: "NOTIFICATION_QUEUED",
  NOTIFICATION_UPDATED: "NOTIFICATION_UPDATED",
  NOTIFICATION_RETRY: "NOTIFICATION_RETRY",
  SUPPLIER_CREATED: "SUPPLIER_CREATED",
  SUPPLIER_UPDATED: "SUPPLIER_UPDATED",
  PURCHASE_ORDER_CREATED: "PURCHASE_ORDER_CREATED",
  PURCHASE_ORDER_UPDATED: "PURCHASE_ORDER_UPDATED",
  PURCHASE_ORDER_ISSUED: "PURCHASE_ORDER_ISSUED",
  GOODS_RECEIVED: "GOODS_RECEIVED",
  EXPENSE_CREATED: "EXPENSE_CREATED",
} as const

export type EventType = (typeof EventTypes)[keyof typeof EventTypes]

export type DomainEvent<TPayload = unknown> = {
  id: string
  type: EventType
  storeId: string | null
  payload: TPayload
  createdAt: string
  /** Correlation for retries / logs */
  source: "repository" | "system"
}
